# Generated by Django 4.0.2 on 2022-04-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootballTimeSlotTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FootballTurfDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turf_name', models.CharField(max_length=50)),
                ('turf_place', models.CharField(max_length=50)),
                ('turf_morningPrice', models.IntegerField()),
                ('turf_eveningPrice', models.IntegerField()),
                ('turf_phoneNumber', models.CharField(max_length=10)),
                ('turf_address', models.CharField(max_length=70)),
            ],
        ),
    ]
