# Generated by Django 4.0.2 on 2022-04-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TurfBookingApp', '0003_footballtimeslottable_turf_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballtimeslottable',
            name='price',
            field=models.IntegerField(choices=[]),
        ),
    ]
