# Generated by Django 4.0.2 on 2022-04-01 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TurfBookingApp', '0005_alter_footballtimeslottable_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurfBookingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=10)),
                ('hours_need', models.IntegerField(default=1)),
                ('booking_date', models.DateField()),
                ('time_slot', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('note', models.TextField(blank=True)),
                ('book_status', models.CharField(max_length=20)),
                ('turf_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TurfBookingApp.turfdetails')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
