# Generated by Django 4.0.2 on 2022-04-02 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TurfBookingApp', '0006_turfbookingtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='turfbookingtable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turfdetails',
            name='category',
            field=models.CharField(choices=[('football', 'Football'), ('shuttle', 'Shuttle'), ('cricket', 'Cricket')], max_length=20),
        ),
    ]
