# Generated by Django 4.0.2 on 2022-04-02 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TurfBookingApp', '0007_turfbookingtable_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShuttleTimeSlotTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('available', models.BooleanField(default=True)),
                ('turf_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TurfBookingApp.turfdetails')),
            ],
        ),
    ]
