# Generated by Django 4.0.2 on 2022-04-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TurfBookingApp', '0010_turfreviewtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='turfbookingtable',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
