# Generated by Django 4.0.2 on 2022-04-13 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TurfBookingApp', '0010_turfreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='turfreview',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='turf-review'),
            preserve_default=False,
        ),
    ]
