# Generated by Django 4.0.2 on 2022-04-14 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TurfBookingApp', '0011_alter_turfreview_turf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TurfReview',
        ),
    ]
