# Generated by Django 4.0.2 on 2022-03-23 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SportsStoreApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carttable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
