# Generated by Django 4.0.2 on 2022-03-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsStoreApp', '0003_alter_carttable_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carttable',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
