# Generated by Django 4.0.2 on 2022-04-16 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SportsStoreApp', '0006_ordertable'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalOrderTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.IntegerField()),
                ('deliver_date', models.DateField()),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('phone', models.CharField(max_length=10)),
                ('total_price', models.IntegerField()),
                ('no_of_products', models.IntegerField()),
                ('status', models.CharField(choices=[('not paid', 'not paid'), ('payment confirmed', 'payment confirmed')], default='payment confirmed', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
