# Generated by Django 4.0.2 on 2022-04-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsStoreApp', '0007_finalordertable'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalordertable',
            name='paymentId',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
