# Generated by Django 4.0.2 on 2022-04-23 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportsStoreApp', '0008_finalordertable_paymentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalordertable',
            old_name='paymentId',
            new_name='payment_id',
        ),
    ]
