# Generated by Django 4.0.2 on 2022-04-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsStoreApp', '0010_rename_deliver_date_finalordertable_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalordertable',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Success', 'success'), ('Failed', 'failed'), ('Cancelled', 'cancelled'), ('Refunded', 'refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Success', 'success'), ('Failed', 'failed'), ('Cancelled', 'cancelled'), ('Refunded', 'refunded')], default='pending', max_length=100),
        ),
    ]
