# Generated by Django 4.0.2 on 2022-04-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsStoreApp', '0011_alter_finalordertable_status_alter_ordertable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalordertable',
            name='signature_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
