# Generated by Django 4.0.2 on 2022-04-25 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportsStoreApp', '0012_finalordertable_signature_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalordertable',
            old_name='payment_id',
            new_name='razorpay_orderId',
        ),
        migrations.RenameField(
            model_name='finalordertable',
            old_name='signature_id',
            new_name='razorpay_signatureId',
        ),
    ]
