# Generated by Django 4.0.2 on 2022-04-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsStoreApp', '0013_rename_payment_id_finalordertable_razorpay_orderid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalordertable',
            name='razorpay_paymentId',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
