# Generated by Django 4.0.2 on 2022-04-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsStoreApp', '0015_alter_finalordertable_razorpay_orderid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalordertable',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('refunded', 'refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('refunded', 'refunded')], default='pending', max_length=100),
        ),
    ]
