# Generated by Django 4.0.2 on 2022-02-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='all sports', max_length=20)),
                ('subcategory', models.CharField(choices=[('team sports', 'Team Sports'), ('footwear', 'Footwear'), ('cycling', 'Cycling'), ('gym accessories', 'Gym Accessories'), ('activewear', 'Activewear'), ('sports sunglasses', 'Sports Sunglasses')], max_length=20)),
                ('childcategory', models.CharField(max_length=20)),
            ],
        ),
    ]
