# Generated by Django 4.0.2 on 2022-03-05 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='all sports', max_length=20)),
                ('subcategory', models.CharField(choices=[('team sports', 'Team Sports'), ('footwear', 'Footwear'), ('cycling', 'Cycling'), ('gym accessories', 'Gym Accessories'), ('activewear', 'Activewear'), ('sports sunglasses', 'Sports Sunglasses')], max_length=30)),
                ('product_name', models.CharField(max_length=50)),
                ('product_gender_for', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('all', 'All')], max_length=10)),
                ('product_offer', models.BooleanField(default=False)),
                ('product_offer_details', models.CharField(default='no offer', max_length=50)),
                ('product_actual_price', models.IntegerField()),
                ('product_selling_price', models.IntegerField()),
                ('product_size', models.CharField(blank=True, max_length=20)),
                ('product_stock', models.IntegerField()),
                ('product_brand', models.CharField(max_length=35)),
                ('product_color', models.CharField(blank=True, max_length=25)),
                ('product_image', models.ImageField(upload_to='product_images')),
                ('product_addondate', models.DateField(auto_now_add=True)),
                ('childcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Index.categories')),
            ],
        ),
    ]
