# Generated by Django 4.0.2 on 2022-03-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0002_productsdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsdetails',
            name='product_details',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
