# Generated by Django 4.0.2 on 2022-03-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0005_alter_productsdetails_product_actual_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsdetails',
            name='product_size',
            field=models.CharField(max_length=20),
        ),
    ]
